[project]
name = "ant-comp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "prosapia[modal]",
]

[tool.uv.sources]
prosapia = { git = "https://github.com/jlmoraleshellin/prosapia", branch = "dev" }

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]